# -*- coding: utf-8 -*-
"""Patterns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mjwegvVb0jVF5bjseeS409XXGaJ7czYN
"""

n = 4

for i in range(n, 0, -1):
    print('*' * i)

num = 10
rows = 3

for i in range(1, rows + 1):
    for j in range(i):
        print(num, end='')
        num += 1
    print()

n = 4

for i in range(n):
    for j in range(i + 1):
        print(chr(68 - j), end='')
    print()

rows = 4

for i in range(rows):
    num = 10
    for j in range(i + 1):
        print(num, end='')
        num += 1
    print()

n = 4

for i in range(n):
    for j in range(i + 1):
        print(chr(65 + j), end='')
    print()

n = 4

for i in range(n):
    for j in range(n - i):
        print(chr(68 - j), end='')
    print()

n = 5

for i in range(1, n + 1):
    for j in range(1, i + 1):
        if j % 2 == 0:
            print(2, end='')
        else:
            print(1, end='')
    print()

n = 4
char_code = 70  # Starting with 'F' (ASCII 70)

for i in range(n):
    for j in range(i + 1):
        print(chr(char_code), end='')
        char_code += 2  # Skip one character each time
    print()

n = 4

for i in range(n):
    print(' ' * i, end='')

    print('*' * (n - i))

n = 4

for i in range(1, n + 1):
    for j in range(1, i + 1):
        print(j, end='')
    print()

n = 4
num = 1

for i in range(1, n + 1):
    for j in range(i):
        print(num, end='')
        num += 1
    print()

n = 4
num = 10

for i in range(1, n + 1):
    for j in range(i):
        print(num, end='')
        num -= 1
    print()

n = 4

for i in range(1, n + 1):
    for j in range(i):
        print(chr(65 + j), end='')
    print()

rows = 3
char_code = 65  # ASCII for 'A'

for i in range(1, rows + 1):
    for j in range(i):
        print(chr(char_code), end='')
        char_code += 1
    print()

rows = 3
start_chars = [90, 88, 84]  # ASCII codes for 'Z', 'X', 'T'

for i in range(rows):
    start = start_chars[i]
    for j in range(i + 1):
        print(chr(start - j), end='')
    print()

n = 5

for i in range(1, n + 1):
    for j in range(1, i + 1):

        if j == 1 or i == n or i == j:
            print('*', end=' ')
        else:
            print(' ', end=' ')
    print()

n = 4
num = 1
char_code = ord('a')

for i in range(1, n + 1):
    for j in range(i):
        print(num, chr(char_code), end=' ')
        num += 1
        char_code += 1
    print()

n = 5

for i in range(1, n + 1):
    print('*' * i)

n = 4

for i in range(1, n + 1):
    for j in range(1, i + 1):
        print(j, end='')
    print()

n = 4
num = 1

for i in range(1, n + 1):
    for j in range(i):
        print(num, end='')
        num += 1
    print()

n = 5

for i in range(n, 0, -1):
    print('*' * i)

n = 4

for i in range(n, 0, -1):
    for j in range(i):
        print(chr(65 + j), end='')
    print()

n = 4

for i in range(1, n + 1):
    print(str(i) * i)

n = 4

for i in range(n):
    for j in range(n, i, -1):
        print(j, end='')
    print()

n = 4

for i in range(1, n + 1):
    for j in range(i):
        print(chr(65 + j), end='')
    print()

n = 5

for i in range(n, 0, -1):
    for j in range(1, i + 1):
        print(j, end='')
    print()

n = 6
start_char = ord('F')

for i in range(n):
    for j in range(n - i):
        print(chr(start_char - j), end='')
    print()

n = 5

for i in range(n):
    a = ' ' * i
    b = '*' * (n - i)
    print(a+b)

n = 5
for i in range(n, 0, -1):
    for k in range(1, i + 1):
        if (k == 1 or i == n or i == k):
            print("*", end=" ")
        else:
            print(" ", end=" ")
    print()

n = 5
for i in range(n):
    for j in range(n):
        if i == n - 1:
            print("*", end=" ")
        elif j == i:
            print("*", end=" ")
        elif j < i:
            print("-", end=" ")
        else:
            print(" ", end=" ")
    print()